- name: get volume groups
  command: vgdisplay -s
  register: volume_group_output

- name: check for vol group
  fail: msg="volume group exists"
  when: volume_group in volume_group_output.stdout

- name: add volume group
  lvg:  vg={{ volume_group }} pesize=1048576 state=present pvs={{ physical_drive }} pesize=8
